#!/bin/bash
# ============================================================
# MeetingMind — Fresh Start (Complete Redeploy)
# This script runs the full setup from Day 1 to Day 6
# ============================================================

set -e  # Exit on error

echo "============================================================"
echo "🚀 MeetingMind Fresh Start"
echo "============================================================"
echo ""
echo "This script will:"
echo "  1. Clean up ALL existing GCP resources"
echo "  2. Run Day 1 setup (GCP infrastructure)"
echo "  3. Guide you through database schema setup"
echo "  4. Deploy to Cloud Run with ADK built-in UI"
echo ""
echo "⏱️  Total time: ~15-20 minutes (mostly Cloud SQL creation)"
echo ""

# ── STEP 0: Get PROJECT_ID ────────────────────────────────────
echo "============================================================"
echo "Step 0: Project Configuration"
echo "============================================================"
echo ""

# Try to get current project
CURRENT_PROJECT=$(gcloud config get-value project 2>/dev/null || echo "")

if [ -n "$CURRENT_PROJECT" ]; then
    echo "Current gcloud project: $CURRENT_PROJECT"
    read -p "Use this project? (y/n): " use_current
    if [ "$use_current" = "y" ] || [ "$use_current" = "Y" ]; then
        export PROJECT_ID=$CURRENT_PROJECT
    else
        read -p "Enter your GCP Project ID: " PROJECT_ID
        gcloud config set project $PROJECT_ID
    fi
else
    read -p "Enter your GCP Project ID: " PROJECT_ID
    gcloud config set project $PROJECT_ID
fi

echo ""
echo "✓ Using project: $PROJECT_ID"
echo ""

# Update .env with PROJECT_ID for cleanup script
if [ -f .env ]; then
    sed -i.bak "s/PROJECT_ID=.*/PROJECT_ID=$PROJECT_ID/" .env
    rm .env.bak
else
    echo "PROJECT_ID=$PROJECT_ID" > .env
fi

# ── STEP 1: Cleanup existing resources ────────────────────────
echo "============================================================"
echo "Step 1: Cleanup (if resources exist)"
echo "============================================================"
echo ""

bash cleanup_gcp.sh

# ── STEP 2: Update day1_gcp_setup.sh with PROJECT_ID ──────────
echo ""
echo "============================================================"
echo "Step 2: Updating day1_gcp_setup.sh with your PROJECT_ID..."
echo "============================================================"
echo ""

# Create a temporary version with the PROJECT_ID filled in
sed "s/export PROJECT_ID=\"your-project-id\"/export PROJECT_ID=\"$PROJECT_ID\"/" day1_gcp_setup.sh > /tmp/day1_setup_temp.sh
chmod +x /tmp/day1_setup_temp.sh

# ── STEP 3: Run Day 1 setup ───────────────────────────────────
echo ""
echo "============================================================"
echo "Step 3: Running Day 1 GCP Setup..."
echo "============================================================"
echo ""
echo "⏱️  This takes 10-15 minutes (Cloud SQL creation is slow)"
echo ""

bash /tmp/day1_setup_temp.sh

# Capture the output variables
export DB_HOST=$(gcloud sql instances describe meetingmind-db --format="value(ipAddresses[0].ipAddress)")
export PROJECT_NUMBER=$(gcloud projects describe $PROJECT_ID --format="value(projectNumber)")
export SERVICE_ACCOUNT="meetingmind-sa@${PROJECT_ID}.iam.gserviceaccount.com"

echo ""
echo "✓ Day 1 setup complete!"
echo ""

# ── STEP 4: Update .env file ──────────────────────────────────
echo "============================================================"
echo "Step 4: Updating .env file..."
echo "============================================================"
echo ""

cat > .env << EOF
# ============================================================
# MeetingMind — Environment Variables
# Auto-generated by fresh_start.sh
# ============================================================

# GCP Project Configuration
PROJECT_ID=$PROJECT_ID
PROJECT_NUMBER=$PROJECT_NUMBER

# Service Account Configuration
SA_NAME=meetingmind-sa
SERVICE_ACCOUNT=$SERVICE_ACCOUNT

# GCP Region
REGION=asia-south1

# Gemini Model
MODEL=gemini-2.5-flash

# Cloud SQL Postgres Configuration
DB_HOST=$DB_HOST
DB_NAME=meetingmind
DB_USER=meetingmind_user
DB_PASSWORD=MeetingMind@2026!
DB_PORT=5432
EOF

echo "✓ .env file updated"
echo ""

# ── STEP 5: Database schema setup ─────────────────────────────
echo "============================================================"
echo "Step 5: Database Schema Setup"
echo "============================================================"
echo ""
echo "⚠️  MANUAL STEP REQUIRED:"
echo ""
echo "1. Connect to Cloud SQL:"
echo "   gcloud sql connect meetingmind-db --user=meetingmind_user --database=meetingmind"
echo ""
echo "2. When connected, paste the contents of schema.sql"
echo "   (The password is: MeetingMind@2026!)"
echo ""
echo "3. After running the schema, exit psql with: \\q"
echo ""
read -p "Press Enter when you've completed the database setup..."
echo ""

# ── STEP 6: Deploy to Cloud Run ───────────────────────────────
echo "============================================================"
echo "Step 6: Deploying to Cloud Run..."
echo "============================================================"
echo ""

bash day6_deploy.sh

# ── COMPLETION ─────────────────────────────────────────────────
echo ""
echo "============================================================"
echo "🎉 FRESH START COMPLETE!"
echo "============================================================"
echo ""
echo "Your MeetingMind is now deployed!"
echo ""
echo "Service URL (use this one):"
SERVICE_URL=$(gcloud run services describe meetingmind --project=$PROJECT_ID --region=asia-south1 --platform=managed --format="value(status.url)")
echo "  $SERVICE_URL"
echo ""
echo "Test the API:"
echo "  curl -X POST $SERVICE_URL/run \\"
echo "    -H 'Content-Type: application/json' \\"
echo "    -d '{\"appName\":\"meetingmind\",\"userId\":\"test\",\"sessionId\":\"s1\",\"newMessage\":{\"role\":\"user\",\"parts\":[{\"text\":\"What tasks are pending?\"}]}}'"
echo ""
echo "============================================================"
