"""
MeetingMind — Google Workspace Tools
Saves meeting docs to Google Cloud Storage (public HTML) and searches Drive.
GCS is used instead of Google Drive because service accounts have no personal Drive storage.
"""

import logging
import os
import re
import datetime
import psycopg2
from typing import Optional
from google.adk.tools.tool_context import ToolContext


def _get_db_conn():
    return psycopg2.connect(
        host=os.getenv("DB_HOST"),
        dbname=os.getenv("DB_NAME"),
        user=os.getenv("DB_USER"),
        password=os.getenv("DB_PASSWORD"),
        port=int(os.getenv("DB_PORT", 5432)),
    )


def _build_html(title: str, summary: str, tasks_markdown: str) -> str:
    """Render meeting summary as a styled HTML page."""
    tasks_html = ""
    if tasks_markdown:
        # Convert markdown-ish task list to HTML lines
        lines = []
        for line in tasks_markdown.splitlines():
            line = line.strip()
            if not line:
                continue
            line = re.sub(r"\*\*(.*?)\*\*", r"<strong>\1</strong>", line)
            if line.startswith("- ") or line.startswith("* "):
                lines.append(f"<li>{line[2:]}</li>")
            else:
                lines.append(f"<p>{line}</p>")
        tasks_html = f"""
        <section>
          <h2>Action Items</h2>
          <ul>{''.join(lines)}</ul>
        </section>"""

    summary_html = summary.replace("\n", "<br>")
    generated = datetime.datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC")

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{title}</title>
  <style>
    body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
           max-width: 860px; margin: 40px auto; padding: 0 24px; color: #1a1a2e; }}
    h1   {{ font-size: 1.8rem; color: #0066cc; border-bottom: 2px solid #0066cc;
           padding-bottom: 8px; }}
    h2   {{ font-size: 1.2rem; color: #444; margin-top: 32px; }}
    ul   {{ line-height: 1.9; }}
    li   {{ margin-bottom: 4px; }}
    footer {{ margin-top: 48px; font-size: 0.8rem; color: #999; }}
  </style>
</head>
<body>
  <h1>📋 {title}</h1>
  <section>
    <h2>Summary</h2>
    <p>{summary_html}</p>
  </section>
  {tasks_html}
  <footer>Generated by MeetingMind — AI Meeting Intelligence · {generated}</footer>
</body>
</html>"""


def create_meeting_doc(
    tool_context: ToolContext,
    title: str,
    summary: str,
    tasks_markdown: str = "",
) -> dict:
    """Save meeting summary as a public HTML page in Google Cloud Storage. Returns URL.

    Args:
        tool_context: ADK tool context.
        title: Document title (usually the meeting name).
        summary: Full meeting summary text.
        tasks_markdown: Action items formatted as markdown (optional).

    Returns:
        dict with doc_url and status.
    """
    try:
        from google.cloud import storage as gcs

        project_id = os.environ.get("PROJECT_ID")
        bucket_name = os.environ.get(
            "GCS_DOCS_BUCKET",
            f"meetingmind-docs-{project_id}" if project_id else "meetingmind-docs",
        )

        client = gcs.Client(project=project_id)

        # Create bucket if it doesn't exist
        try:
            bucket = client.get_bucket(bucket_name)
        except Exception:
            bucket = client.create_bucket(bucket_name, location="us-central1")
            # Allow public reads
            bucket.iam_configuration.uniform_bucket_level_access_enabled = True
            bucket.patch()
            policy = bucket.get_iam_policy(requested_policy_version=3)
            policy.bindings.append(
                {
                    "role": "roles/storage.objectViewer",
                    "members": {"allUsers"},
                }
            )
            bucket.set_iam_policy(policy)
            logging.info(f"Created GCS bucket: {bucket_name}")

        # Build a URL-safe object name
        slug = re.sub(r"[^a-z0-9]+", "-", title.lower()).strip("-")[:80]
        ts = datetime.datetime.utcnow().strftime("%Y%m%d-%H%M%S")
        blob_name = f"meetings/{ts}-{slug}.html"

        html_content = _build_html(title, summary, tasks_markdown)

        blob = bucket.blob(blob_name)
        blob.upload_from_string(html_content, content_type="text/html; charset=utf-8")
        # Public access is granted via bucket-level IAM (allUsers → objectViewer),
        # so per-object ACLs (make_public) must NOT be called with uniform access enabled.

        doc_url = blob.public_url
        logging.info(f"Meeting doc saved to GCS: {doc_url}")

        # Persist doc_url back to the meetings table
        meeting_id = tool_context.state.get("current_meeting_id") if tool_context else None
        if meeting_id:
            try:
                with _get_db_conn() as conn:
                    cur = conn.cursor()
                    cur.execute(
                        "UPDATE meetings SET doc_url = %s WHERE id = %s", (doc_url, str(meeting_id))
                    )
                    conn.commit()
                    cur.close()
            except Exception as db_err:
                logging.warning(f"Could not save doc_url to DB: {db_err}")

        return {
            "status": "success",
            "doc_url": doc_url,
            "title": title,
            "message": f"✅ Meeting doc published: {doc_url}",
        }

    except Exception as e:
        logging.error(f"create_meeting_doc failed: {e}")
        return {
            "status": "error",
            "message": f"Could not save meeting doc: {e}",
            "doc_url": None,
        }


def search_gdrive(tool_context: ToolContext, query: str) -> dict:
    """Search Google Drive for files matching a keyword query.

    Args:
        tool_context: ADK tool context.
        query: Search term (searches file names and full text).

    Returns:
        dict with list of matching files and their URLs.
    """
    try:
        from googleapiclient.discovery import build
        from google.auth import default

        creds, _ = default(scopes=["https://www.googleapis.com/auth/drive.readonly"])
        service = build("drive", "v3", credentials=creds)

        results = (
            service.files()
            .list(
                q=f"(name contains '{query}' or fullText contains '{query}') and trashed=false",
                pageSize=10,
                fields="files(id, name, mimeType, webViewLink, modifiedTime)",
            )
            .execute()
        )

        files = [
            {
                "name": f["name"],
                "url": f.get("webViewLink", ""),
                "type": f["mimeType"].split(".")[-1],
                "modified": f.get("modifiedTime", ""),
            }
            for f in results.get("files", [])
        ]

        return {
            "status": "success",
            "query": query,
            "count": len(files),
            "files": files,
        }

    except Exception as e:
        logging.error(f"search_gdrive failed: {e}")
        return {"status": "error", "message": str(e), "files": []}


def send_meeting_summary_email(
    tool_context: ToolContext,
    to_emails: list,
    subject: str,
    body: str,
) -> dict:
    """Send a meeting summary email via Gmail API.

    Args:
        tool_context: ADK tool context.
        to_emails: List of recipient email addresses.
        subject: Email subject line.
        body: Plain-text or HTML body content.

    Returns:
        dict with send status.
    """
    try:
        import base64
        from email.mime.text import MIMEText
        from googleapiclient.discovery import build
        from google.auth import default

        creds, _ = default(scopes=["https://www.googleapis.com/auth/gmail.send"])
        service = build("gmail", "v1", credentials=creds)

        msg = MIMEText(body, "html")
        msg["to"] = ", ".join(to_emails)
        msg["subject"] = subject
        raw = base64.urlsafe_b64encode(msg.as_bytes()).decode()

        service.users().messages().send(userId="me", body={"raw": raw}).execute()

        return {
            "status": "success",
            "message": f"Email sent to {', '.join(to_emails)}",
            "recipients": to_emails,
        }

    except Exception as e:
        logging.error(f"send_meeting_summary_email failed: {e}")
        return {
            "status": "error",
            "message": (
                f"Could not send email: {e}. "
                "Gmail API requires domain-wide delegation for service accounts."
            ),
        }
